# Available actions:
# [CONSOLE] - execute a command as the console
# [PLAYER] - execute a command as the player (Do not write any /)
# [TITLE] - display a message to the player on the screen (title) (Usage title;subtitle;fadeIn;stay;fadeOut)
# [ACTIONBAR] - display a message to the player above the hotbar (In the action bar)
# [MESSAGE] - send a message to the player in chat
# [PLAY_SOUND] - play a sound to the player (Usage SOUND;VOLUME;PITCH (Volume and pitch are optional))
# [PLAY_SOUND_ALL] - play a sound to all players (Usage SOUND;VOLUME;PITCH (Volume and pitch are optional))
# [EFFECT] - give the player a potion effect (Usage EFFECT;STRENGTH;DURATION (Strength and duration are optional))
# [BROADCAST] - send a message to all players online
# [TELEPORT] - teleport the player (Usage WORLD;X;Y;Z;YAW;PITCH ("yaw" and "pitch" are optional))
# [GAMEMODE] - set the player's game mode (0 or survival | 1 or creative | 2 or adventure | 3 or spectator)
#
# Available placeholders:
# %player% - player's name
# %world% - the world where the player fell into the void
# %world_display_name% - display name of the world (Configured in "messages")
#
# All available sounds can be found here -> https://helpch.at/docs/{server_version}/org/bukkit/Sound.html
# Replace {server_version} with the version of the core on your server
#
# World settings (Left empty to disable)
worlds:
  # World name (Specify the one you need) (You can add as many as you want)
  world:
    # Execution type (When the player reaches the minimum Y coordinate)
    floor:
      # The coordinate below which if the player reaches, actions will be executed
      executing-height: 0
      # Fix for the bug in all similar plugins, where commands are applied to players indefinitely until they leave the coordinates
      # In this case, commands will be repeated every 3 seconds
      repeat-fix: 3
      # Should only one random action from the list be executed?
      random: false
      # Actions
      execute-commands:
        - '[PLAY_SOUND] BLOCK_NOTE_BELL;3'
        - '[PLAYER] spawn'
        - '[TITLE] &aСпасенье;&fТы был спасён от смерти!'
    # Execution type (When the player reaches the maximum Y coordinate)
    roof:
      # The coordinate below which is the player reaches, actions will be executed
      executing-height: 666
      # Fix for the bug in all similar plugins, where commands are applied to players indefinitely until they leave the coordinates
      # In this case, commands will be repeated every 15 seconds
      repeat-fix: 15
      # Should a random action from the list be executed?
      random: true
      # Actions
      execute-commands:
        - '[TITLE] &aHow did you get here?'
        - '[TITLE] ;&eHello!'
        - '[TITLE] &1Use /spawn;&9To teleport to spawn!'
        - '[TITLE] &5Your name %player%;&dWorld you are in %world%'
  # Examples
  spawn:
    floor:
      executing-height: 0
      repeat-fix: 10
      random: false
      execute-commands:
        - '[PLAYER] rtp safe'
  world_nether:
    roof:
      executing-height: 127
      repeat-fix: 120
      execute-commands:
        - '[TITLE] &c&kkkkkkkkkkkkk;&c&kkkkkkkkkkkkkkkkkkkkkkkkk'
  world_the_end:
    floor:
      executing-height: 0
      repeat-fix: 3
      execute-commands:
        - '[PLAYER] spawn'

# Region settings (Left empty to disable)
# Requires WorldGuardEvents to work! You can downloaded it here -> https://www.spigotmc.org/resources/worldguard-events.65176/
regions:
  # Region name (case-insensitive)
  test:
    # Since WorldGuard allows creating regions with the same name in different worlds
    # I added the ability to specify the worlds in which actions will be triggered
    worlds:
      - 'world'
    # Actions when entering the region (Can be deleted to disable)
    on-enter:
      # Should only one random action from the list be executed?
      random: false
      # Actions
      execute-commands:
        - '[MESSAGE] &cYou entered a region owned by someone. &fJust know that you can''t build there!'
    # Actions when leaving the region (Can be deleted to disable)
    on-leave:
      # Should only one random action from the list be executed?
      random: false
      # Actions
      execute-commands:
        - '[MESSAGE] &aYou left a region owned by someone.'
  # Example
  rtp:
    worlds:
      - 'spawn'
    on-enter:
      random: false
      execute-commands:
        - '[PLAYER] rtp'

# Player connection/disconnection settings (Can be left empty to disable)
player:
  # When a player connects to the server (Can be deleted to disable)
  on-server-join:
    # Should a random action from the list be executed?
    random: false
    # Actions
    execute-commands:
      - '[ACTIONBAR] &6Welcome!'
      - '[BROADCAST] &a[+] &f%player%'
      - '[PLAY_SOUND_ALL] BLOCK_NOTE_BELL;1;1'
  # When a player disconnects from the server (Can be deleted to disable)
  on-server-leave:
    # Should a random action from the list be executed?
    random: false
    # Actions
    execute-commands:
      - '[BROADCAST] &c[-] &f%player%'
  # When a player died
  on-death:
    # Should a random action from the list be executed?
    random: false
    # If set to true, then the player will not be offered to respawn, and it will happen instantly automatically
    instantly-respawn: false
    # Actions
    execute-commands:
      - '[TITLE] ;&cYou died :(;10;40;20'
      - '[SOUND] ENTITY_PLAYER_LEVELUP'

# Messages
messages:
  # Message when the plugin is reloaded
  reload-message: '&aThe VoidFall plugin has been successfully reloaded.'
  # Messages if there are not enough permissions to use the command
  no-permission: '&cSorry, but you do not have enough permissions to use this command.'
  # World names that will be displayed in %world_display_name%
  worlds-display-names:
    world: '&aworld'
    world_nether: '&cnether'
    world_the_end: '&dend'

# Required if sounds suddenly stop working or messages are not displayed and so on.
debug-mode: false
# Config version (Needed to prevent errors when updating the plugin)
# Do not change otherwise your config will be backed up and reset to default
config-version: 1.3
# Should updates be checked? May be useful if bugs are found and the plugin is updated, so you don't have to monitor yourself
check-updates: true