# Допустимые исполнители:
# [CONSOLE] - выполнить действие от имени консоли
# [PLAYER] - выполнить действие от имени игрока (Писать / не нужно!)
# [MESSAGE] - Отобразить сообщение игроку в чате
# [BROADCAST] - Вывести сообщение всем игрокам на сервере
# [ACTIONBAR] - Вывести сообщение игроку над хотбаром (В екшбаре)
# [TITLE] - Вывести сообщение игроку на экран
# Формат: [TITLE] title;subtitle;fadeIn;stay;fadeOut (Необязательно писать все параметры, хватит и одного, но обязательно сохранять последовательность!!!)
# [PLAY_SOUND] - Проиграть музыку игроку
# Формат: [PLAY_SOUND] soundName;volume;pitch (Необязательно писать все параметры, хватит и одного, но обязательно сохранять последовательность!!!)
# [EFFECT] - Применить эффект к игроку (duration указывать в секундах!)
# Формат: [EFFECT] potionEffectName;duration;amplifier (Необязательно писать все параметры, хватит и одного, но обязательно сохранять последовательность!!!)
#
# Доступные плейсхолдеры от плагина: (А так-же вы можете ВЕЗДЕ использовать плейсхолдеры из PlaceholderAPI)
# %player% - Ник игрока
# %world% - Мир в котором игрок упал в пустоту
#
# Плейсхолдеры можно вставить в любое место, кроме названия мира!
#
# Настройки миров (Можно оставить пустым и тогда будет выключено)
worlds:
  # Название мира (Указывайте нужное вам) (Можно добавить сколько угодно)
  world:
    # Тип выполнения (Когда игрок достигнет минимальной координаты по Y)
    floor:
      # Координата ниже которой если игрок достигнет, то будут выполнены действия
      executing-height: 0
      # Фикс бага во всех подобных плагина, из-за которого команды применяются к игрокам бесконечность раз пока они не покинут координаты
      # В данном случае команды будут повторяться каждые 3 секунды
      repeat-fix: 3
      # Нужно ли выбрать рандомно одно действие из списка и использовать его
      random: false
      # Нужно ли убирать урон от бездны? (Необязательно)
      disable-void-damage: '%luckperms_has_permission_void.fall%'
      # Действия
      execute-commands:
        - '[PLAY_SOUND] BLOCK_NOTE_BELL;3'
        - '[PLAYER] spawn'
        - '[TITLE] &aСпасенье;&fТы был спасён от смерти!'
    # Тип выполнения (Когда игрок достигнет максимальной координаты по Y)
    roof:
      # Координата ниже которой если игрок достигнет, то будут выполнены действия
      executing-height: 666
      # Фикс бага во всех подобных плагина, из-за которого команды применяются к игрокам бесконечность раз пока они не покинут координаты
      # В данном случае команды будут повторяться каждые 15 секунд
      repeat-fix: 15
      # Нужно ли выбрать рандомно одно действие из списка и использовать его
      # Можно не писать, тогда будет выключено
      random: true
      # Действия
      execute-commands:
        - '[TITLE] &aКак ты сюда добрался?'
        - '[TITLE] ;&eПривет %player_name%!'
        - '[TITLE] &1Используй /spawn;&9Чтобы телепортироваться на спавн!'
        - '[TITLE] &5Твой ник %player%;&dМир в котором ты находишься %world%'
        - '[EFFECT] blindness;3;1'
  # Примеры
  spawn:
    floor:
      executing-height: 0
      repeat-fix: '%math_4+5-2*3%' # Тут будет 3
      random: false
      execute-commands:
        - '[PLAYER] rtp safe'
  world_nether:
    roof:
      executing-height: '%math_126+1%' # Тут будет 127
      repeat-fix: 120
      execute-commands:
        - '[TITLE] &c&kkkkkkkkkkkkk;&c&kkkkkkkkkkkkkkkkkkkkkkkkk'
  world_the_end:
    floor:
      executing-height: 0
      repeat-fix: 3
      execute-commands:
        - '[PLAYER] spawn'

# Сообщения
messages:
  # Сообщение при перезагрузке плагина
  reload-message: '&aПлагин VoidFall успешно перезагружен.'
  # Сообщения если не хватает прав на использование команды
  no-permission: '&cИзвини, но у тебя не хватает прав на использование данной команды.'

# Нужно если у вас вдруг перестанут работать к примеру звуки или отображаться сообщения.
debug-mode: false
# Версия конфига (Нужна, чтобы при обновлениях плагина не было ошибок)
# Не стоит менять иначе ваш конфиг будет превращен в бекап и сброшен до заводских настроек
config-version: 1.2
# Нужно ли проверять обновления? Может быть полезно если будут найдены баги и плагин будет обновлён, а вам не прийдется самому следить
# Но изначально отключено, так-как почти все выключает
check-updates: false