name: VoidFall
version: '${project.version}'
main: noslowdwn.voidfall.VoidFall
authors: [ noslowdwn ]
description: Execute a command to a player who has reached the cords by Y that u specified
softdepend: [ PlaceholderAPI ]

commands:
  voidfall: {}

permissions:
  voidfall.reload:
    default: op
    description: Allows you to reload plugin
  voidfall.updates:
    default: false
    description: Allows you to see is there any updates